import { NextResponse } from "next/server";

import { SLACK_BOT_SCOPES, getInstaller, getOAuthRedirectUri } from "@/lib/slack/install-provider";

/** Starts Slack OAuth installation. State (CSRF) is generated by the InstallProvider's stateStore. */
export async function GET() {
  const installer = getInstaller();
  const url = await installer.generateInstallUrl({
    scopes: [...SLACK_BOT_SCOPES],
    redirectUri: getOAuthRedirectUri(),
  });

  return NextResponse.redirect(url);
}
